<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>KeyPulse.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="KeyPulse.ico" />
    <EmbeddedResource Include="NativeLibs\av_libglesv2.dll" />
    <EmbeddedResource Include="NativeLibs\libHarfBuzzSharp.dll" />
    <EmbeddedResource Include="NativeLibs\libSkiaSharp.dll" />
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Windows.Extensions" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\click.wav" />
    <EmbeddedResource Include="Assets\close.wav" />
    <EmbeddedResource Include="Assets\error.wav" />
  </ItemGroup>
</Project>

